package tests

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestE2E_SupportMatrixGenerator(t *testing.T) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve test file path")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(file), ".."))
	output := filepath.Join(t.TempDir(), "API_SUPPORT.md")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "go", "run", "./internal/cmd/gensupport", "-output", output)
	cmd.Dir = root
	if combined, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generate support matrix: %v\n%s", err, combined)
	}

	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	checkedIn, err := os.ReadFile(filepath.Join(root, "docs", "API_SUPPORT.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated, checkedIn) {
		t.Fatal("generator output differs from docs/API_SUPPORT.md")
	}

	text := string(generated)
	for _, want := range []string{
		"<!-- Code generated by go generate; DO NOT EDIT. -->",
		"| Claude Code |", "| Codex |", "| Kimi |", "| TraeX |", "| OpenCode |",
		"`WithModel(model)`", "`(*Agent).GetSession(ctx, id)`", "`KindToolResult`",
		"OpenCode 通过 ACP session config 设置模型",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated matrix is missing %q", want)
		}
	}
	if strings.Contains(text, "依赖 ACP capability") {
		t.Fatal("generated matrix contains ambiguous ACP capability wording")
	}
}
