package tests

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

func TestE2E_SupportMatrixGenerator(t *testing.T) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve test file path")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(file), ".."))
	output := filepath.Join(t.TempDir(), "API_SUPPORT.md")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "./scripts/generate-support-matrix.sh", "-output", output)
	cmd.Dir = root
	if combined, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generate support matrix: %v\n%s", err, combined)
	}

	generated, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	checkedIn, err := os.ReadFile(filepath.Join(root, "docs", "API_SUPPORT.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated, checkedIn) {
		t.Fatal("generator output differs from docs/API_SUPPORT.md")
	}

	text := string(generated)
	for _, want := range []string{
		"<!-- Code generated by scripts/generate-support-matrix.sh; DO NOT EDIT. -->",
		"| Claude Code |", "| Codex |", "| Kimi |", "| TraeX |", "| OpenCode |",
		"`agent.configure.model`", "`session.retrieve`", "`event.tool_result`",
		"OpenCode selects the model through ACP session configuration",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("generated matrix is missing %q", want)
		}
	}
	if strings.Contains(text, "depends on ACP capability") {
		t.Fatal("generated matrix contains ambiguous ACP capability wording")
	}
	for _, forbidden := range []string{"(*Agent)", "(*Session)", "WithModel("} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("generated matrix contains language-specific API terminology %q", forbidden)
		}
	}
	for _, char := range text {
		if char >= '\u4e00' && char <= '\u9fff' {
			t.Fatalf("generated matrix contains non-English text: %q", char)
		}
	}
}
