package driver

import (
	"fmt"

	"github.com/google/uuid"
)

// AgentKey is the cache key for an AgentProcess within a Registry. Typically the
// host's agent UUID (as a string); string-typed so it works directly as a map
// key and travels through logs without allocation.
type AgentKey = string

// SessionID is a runtime-assigned session identifier (Claude's sessionId,
// Codex's thread id, an ACP session id, …). Runtimes own the canonical form; the
// SDK never synthesises one.
type SessionID = string

// RunID identifies a single submission in flight so callers can correlate Send
// call with its Completed/Failed events. Generated by the SDK.
type RunID = string

// NewRunID mints a fresh RunID.
func NewRunID() RunID {
	return uuid.NewString()
}

// FormatRunID is a tiny helper for log lines that want a short, stable label.
func FormatRunID(id RunID) string {
	if id == "" {
		return "<none>"
	}
	return fmt.Sprintf("run:%s", id)
}
